// File generated by FlutterFire CLI — project: posefit-964dd

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Kinetra targets Android only.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcyBYB4EmJJ4a4g0I6DrB9Q3rp0zngsrs',
    appId: '1:963935721741:android:fe6e78ec321c3cca26b844',
    messagingSenderId: '963935721741',
    projectId: 'kinetra-513fe',
    storageBucket: 'kinetra-513fe.firebasestorage.app',
  );

}